include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  OPT_IN_TEST_PREVIOUS_MAJOR: 0
  OPT_IN_TEST_NEXT_MINOR: 1
  OPT_IN_TEST_NEXT_MAJOR: 0
  RUN_JOB_UPGRADE_STATUS: 0
  OPT_IN_TEST_CURRENT: 1
  CORE_STABLE: '11.x-dev'
  _PHPUNIT_CONCURRENT: 1
  _PHPUNIT_EXTRA: --verbose
  _CSPELL_IGNORE_PATHS: "'.cspell-project-words.txt', 'tests/assets'"
pages:
  stage: .post

cspell:
  allow_failure: false
stylelint:
  allow_failure: false
phpcs:
  allow_failure: false
phpstan:
  allow_failure: false
